apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: vctvg/kbtest:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        ports:
        - containerPort: 80
        env:
        - name: branch
          value: <BRANCH_NAME>

