apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: vctvg/kbtest:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        ports:
        - containerPort: 8080
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
  labels:
    app: jenkins-demo
spec:
  selector:
    app: jenkins-demo
  type: NodePort
  ports:
  - name: web
    port: 8080
    nodePort: 30001

